import type { ListeningSection, ObjectiveQuestion } from "../shared/practiceTypes";

const choice = (number: number, prompt: string, options: string[], answer: string, evidence: string, explanation: string): ObjectiveQuestion => ({
  id: `listening-${number}`,
  number,
  kind: "single",
  prompt,
  options,
  acceptedAnswers: [answer],
  evidence,
  explanation,
});

const text = (number: number, prompt: string, answers: string[], evidence: string, explanation: string): ObjectiveQuestion => ({
  id: `listening-${number}`,
  number,
  kind: "text",
  prompt,
  acceptedAnswers: answers,
  evidence,
  explanation,
});

export const LISTENING_SECTIONS: ListeningSection[] = [
  {
    id: "community-course",
    title: "Joining a community course",
    context: "Section 1 · A caller registers for an evening class",
    segments: [
      { speaker: "Receptionist", text: "Good morning, Riverside Community Centre. How can I help?" },
      { speaker: "Caller", text: "I'd like to join an evening class. I was thinking about pottery, but I need something after work." },
      { speaker: "Receptionist", text: "The beginner pottery class is on Tuesday evenings. It begins at six thirty and finishes at eight." },
      { speaker: "Caller", text: "Tuesday is perfect. Where is it held?" },
      { speaker: "Receptionist", text: "In Studio Two, beside the small garden. The tutor is Mara Velez. That's V E L E Z." },
      { speaker: "Caller", text: "Great. How much is the course?" },
      { speaker: "Receptionist", text: "It's eighty-five pounds for eight weeks. Clay and basic materials are included, but you should bring an apron and an old towel." },
      { speaker: "Caller", text: "Do I need to buy any tools?" },
      { speaker: "Receptionist", text: "No. Shared tools are provided. We ask for an emergency contact, though." },
      { speaker: "Caller", text: "Use my sister, Nina Chen. Her number is zero seven seven zero zero, four eight two, six one nine." },
      { speaker: "Receptionist", text: "Thanks. Finally, would you like confirmation by text or email?" },
      { speaker: "Caller", text: "Email, please. I sometimes miss text messages at work." },
    ],
    questions: [
      text(1, "Which class does the caller choose?", ["pottery", "beginner pottery"], "The caller chooses the beginner pottery class.", "The selected subject is pottery."),
      text(2, "On which day is the class held?", ["Tuesday", "Tuesdays"], "The beginner pottery class is on Tuesday evenings.", "The day is stated when the class is introduced."),
      text(3, "What time does the class begin?", ["6:30", "6.30", "six thirty", "6:30 pm", "6.30 pm"], "It begins at six thirty.", "The answer is the starting time, not the finishing time."),
      text(4, "Complete the room name: Studio ______.", ["2", "two"], "In Studio Two, beside the small garden.", "The class location is Studio Two."),
      text(5, "What is the tutor's surname?", ["Velez"], "The tutor is Mara Velez. That's V E L E Z.", "The surname is spelled aloud."),
      text(6, "How much does the eight-week course cost? Write the number only.", ["85", "eighty five", "eighty-five"], "It's eighty-five pounds for eight weeks.", "The fee is 85 pounds."),
      choice(7, "Which item is included in the fee?", ["An apron", "Clay", "An old towel"], "Clay", "Clay and basic materials are included.", "The apron and towel must be brought by the learner."),
      text(8, "What should the caller bring besides an apron?", ["an old towel", "old towel", "a towel", "towel"], "You should bring an apron and an old towel.", "The second personal item is a towel."),
      choice(9, "Who is the emergency contact?", ["The tutor", "The caller's sister", "A work colleague"], "The caller's sister", "Use my sister, Nina Chen.", "Nina Chen is identified as the caller's sister."),
      choice(10, "How should confirmation be sent?", ["By email", "By text", "By post"], "By email", "Email, please.", "The caller chooses email because work texts are easy to miss."),
    ],
  },
  {
    id: "museum-orientation",
    title: "Visitor information at a maritime museum",
    context: "Section 2 · A guide welcomes visitors to a museum",
    segments: [
      { speaker: "Guide", text: "Welcome to Westhaven Maritime Museum. Before you explore, I have a few practical details." },
      { speaker: "Guide", text: "Large bags must be placed in the lockers on the lower level. The lockers are free, but you need a one-pound coin, which is returned when you leave." },
      { speaker: "Guide", text: "Photography is allowed in most galleries, provided that you do not use a flash. The temporary map exhibition is the exception: no photography is permitted there." },
      { speaker: "Guide", text: "Your visit begins in Gallery Three with the film called Tides of Trade. It lasts twelve minutes. After the film, follow the blue line on the floor to the shipbuilding hall." },
      { speaker: "Guide", text: "At one fifteen, there is a live rope-making demonstration in the courtyard. It will move indoors to the workshop if it rains." },
      { speaker: "Guide", text: "Families may borrow an activity pack from the information desk. Please return it before the desk closes at five." },
      { speaker: "Guide", text: "The cafe serves hot food until three thirty and closes at four thirty. The museum itself remains open until six." },
      { speaker: "Guide", text: "Finally, the east staircase is closed for repair. Use the central lift or the west stairs to reach the upper deck." },
    ],
    questions: [
      text(11, "Where are the lockers located?", ["lower level", "the lower level"], "The lockers are on the lower level.", "The location, not the coin requirement, is requested."),
      text(12, "What coin is needed for a locker?", ["one pound", "1 pound", "one-pound", "£1", "1"], "You need a one-pound coin, which is returned.", "A one-pound coin operates the locker."),
      choice(13, "What is prohibited in most galleries?", ["All photography", "Flash photography", "Taking notes"], "Flash photography", "Photography is allowed ... provided that you do not use a flash.", "Only flash use is generally prohibited."),
      choice(14, "Where is all photography prohibited?", ["The shipbuilding hall", "The map exhibition", "Gallery Three"], "The map exhibition", "The temporary map exhibition is the exception: no photography is permitted there.", "This exhibition has the stricter rule."),
      text(15, "In which gallery does the visit begin?", ["3", "three", "gallery 3", "gallery three"], "Your visit begins in Gallery Three.", "The starting gallery is number three."),
      text(16, "How long is the introductory film?", ["12 minutes", "twelve minutes", "12"], "It lasts twelve minutes.", "The requested duration is twelve minutes."),
      text(17, "What colour line leads to the shipbuilding hall?", ["blue"], "Follow the blue line on the floor.", "The route is marked in blue."),
      text(18, "At what time is the rope-making demonstration?", ["1:15", "1.15", "one fifteen", "1:15 pm", "1.15 pm"], "At one fifteen, there is a live rope-making demonstration.", "The event begins at 1:15."),
      choice(19, "Where will the demonstration move if it rains?", ["The cafe", "The workshop", "The upper deck"], "The workshop", "It will move indoors to the workshop if it rains.", "The workshop is the wet-weather location."),
      text(20, "What time does the cafe close?", ["4:30", "4.30", "four thirty", "4:30 pm", "4.30 pm"], "The cafe ... closes at four thirty.", "Hot food ends earlier, but the cafe closes at 4:30."),
    ],
  },
  {
    id: "food-waste-project",
    title: "Planning a student research project",
    context: "Section 3 · Two students discuss a food-waste study",
    segments: [
      { speaker: "Leah", text: "We need to narrow our food-waste project. Comparing every restaurant in town is impossible." },
      { speaker: "Omar", text: "Agreed. What if we study the university cafeteria? We can combine a short customer survey with direct observation." },
      { speaker: "Leah", text: "Observation sounds stronger than asking people to remember what they threw away. But we still need the survey to understand why." },
      { speaker: "Omar", text: "Let's aim for sixty survey responses. We can collect them over three lunch periods rather than a single day." },
      { speaker: "Leah", text: "For observation, we should separate edible leftovers from things like bones and fruit peel." },
      { speaker: "Omar", text: "Yes, and record plate size. Larger plates might encourage people to take more than they need." },
      { speaker: "Leah", text: "Should we weigh every plate?" },
      { speaker: "Omar", text: "That would slow the queue. We could photograph the trays, then use a five-point visual scale." },
      { speaker: "Leah", text: "Good. We must ask permission before photographing, even if no faces appear." },
      { speaker: "Omar", text: "Professor Grant also suggested comparing the first and last half-hour of lunch service. Choice becomes limited near closing time." },
      { speaker: "Leah", text: "I'll draft the survey tonight. Can you create the observation sheet?" },
      { speaker: "Omar", text: "Yes, and I'll contact the cafeteria manager. Let's pilot everything next Monday before collecting the real data." },
    ],
    questions: [
      choice(21, "Why do the students reject studying every restaurant?", ["It would cost too much", "The scope is too large", "Restaurants do not serve lunch"], "The scope is too large", "Comparing every restaurant in town is impossible.", "They need a narrower, manageable setting."),
      choice(22, "Where will the research take place?", ["A town market", "The university cafeteria", "A school kitchen"], "The university cafeteria", "What if we study the university cafeteria?", "They agree on the campus cafeteria."),
      choice(23, "Why does Leah value direct observation?", ["It avoids relying on memory", "It requires no permission", "It explains every cause"], "It avoids relying on memory", "Observation sounds stronger than asking people to remember what they threw away.", "Observation records behaviour rather than recalled behaviour."),
      text(24, "How many survey responses do they want?", ["60", "sixty"], "Let's aim for sixty survey responses.", "The target sample is sixty."),
      text(25, "Across how many lunch periods will surveys be collected?", ["3", "three"], "We can collect them over three lunch periods.", "Collection is spread across three lunches."),
      choice(26, "Which waste will be classified separately?", ["Edible leftovers", "Paper receipts", "Cooking oil"], "Edible leftovers", "We should separate edible leftovers from things like bones and fruit peel.", "The study distinguishes avoidable edible waste."),
      text(27, "What physical feature of the meal will they record?", ["plate size", "the plate size"], "Record plate size.", "They suspect larger plates may affect serving behaviour."),
      choice(28, "How will the quantity left on trays be estimated?", ["By weighing every plate", "With a five-point visual scale", "By asking the manager"], "With a five-point visual scale", "Photograph the trays, then use a five-point visual scale.", "The scale is chosen to avoid slowing the queue."),
      choice(29, "What must the students obtain before taking photographs?", ["Permission", "A larger camera", "The survey results"], "Permission", "We must ask permission before photographing.", "No faces does not remove the consent requirement."),
      text(30, "When will they pilot the research tools?", ["next Monday", "Monday"], "Let's pilot everything next Monday.", "The pilot precedes real data collection."),
    ],
  },
  {
    id: "urban-cooling",
    title: "How cities cool hot neighbourhoods",
    context: "Section 4 · A lecture on urban heat reduction",
    segments: [
      { speaker: "Lecturer", text: "Today's topic is urban cooling. Cities are often warmer than nearby rural areas because dark surfaces absorb solar energy and buildings restrict air movement." },
      { speaker: "Lecturer", text: "One response is the cool roof: a pale or reflective roof that sends more sunlight back into the atmosphere. Its performance is measured partly by albedo, which means the proportion of incoming light a surface reflects." },
      { speaker: "Lecturer", text: "Cool roofs reduce indoor temperatures most directly on the top floor. Their city-wide effect is smaller if only a few buildings adopt them, so some councils offer rebates to encourage groups of owners to participate." },
      { speaker: "Lecturer", text: "Trees cool streets in two ways. Their leaves provide shade, and water evaporating from leaves removes heat from the air. However, tree species must suit local rainfall. A thirsty species may increase pressure on water supplies." },
      { speaker: "Lecturer", text: "Street geometry matters too. Closely spaced tall buildings can shade pedestrians during the day, yet the same urban canyon may trap heat at night. Designers therefore study both daytime shade and nighttime ventilation." },
      { speaker: "Lecturer", text: "Some cities use permeable pavements that allow rain to enter the ground. When the stored moisture later evaporates, the surface cools. These pavements work poorly where sediment blocks their pores, so regular cleaning is essential." },
      { speaker: "Lecturer", text: "Cooling projects should be evaluated at neighbourhood scale. A park may lower the temperature within its boundary but provide little benefit across a wide road. Routes used by older people and outdoor workers may deserve priority because exposure is unequal." },
      { speaker: "Lecturer", text: "Finally, no single temperature measure tells the whole story. Air temperature, surface temperature, humidity and wind all affect comfort. Good planning combines these measurements with interviews about how residents actually experience heat." },
    ],
    questions: [
      text(31, "What type of surfaces absorb solar energy and contribute to urban heat?", ["dark surfaces", "dark"], "Dark surfaces absorb solar energy.", "Surface colour affects solar absorption."),
      text(32, "What term means the proportion of incoming light reflected by a surface?", ["albedo"], "Albedo ... means the proportion of incoming light a surface reflects.", "The lecturer defines the technical term directly."),
      choice(33, "Where do cool roofs most directly reduce indoor temperature?", ["On the top floor", "In underground rooms", "On shaded streets"], "On the top floor", "Cool roofs reduce indoor temperatures most directly on the top floor.", "The roof has the strongest direct effect immediately below it."),
      choice(34, "Why do some councils offer rebates?", ["To encourage coordinated adoption", "To replace all city trees", "To measure rural temperatures"], "To encourage coordinated adoption", "Councils offer rebates to encourage groups of owners to participate.", "Wider adoption improves the city-scale effect."),
      text(35, "Besides shade, what process allows tree leaves to cool the air?", ["evaporation", "water evaporation"], "Water evaporating from leaves removes heat from the air.", "Evaporation is the second cooling mechanism."),
      choice(36, "What risk comes from choosing a tree species poorly suited to local rainfall?", ["Greater pressure on water supplies", "Less reflective roof paint", "Blocked pavement pores"], "Greater pressure on water supplies", "A thirsty species may increase pressure on water supplies.", "Water demand is the stated trade-off."),
      choice(37, "What can closely spaced tall buildings do at night?", ["Trap heat", "Increase rainfall", "Clean the air automatically"], "Trap heat", "The same urban canyon may trap heat at night.", "Daytime shade can come with a nighttime disadvantage."),
      text(38, "What maintenance do permeable pavements require?", ["regular cleaning", "cleaning"], "Regular cleaning is essential.", "Cleaning prevents sediment from blocking pores."),
      choice(39, "Who may deserve priority in cooling-route planning?", ["Older people and outdoor workers", "Only building owners", "Tourists and drivers"], "Older people and outdoor workers", "Routes used by older people and outdoor workers may deserve priority.", "Their heat exposure may be greater."),
      choice(40, "What should physical heat measurements be combined with?", ["Resident interviews", "Property prices", "Traffic fines"], "Resident interviews", "Good planning combines these measurements with interviews.", "Experience data complements physical measures."),
    ],
  },
];

export const LISTENING_QUESTIONS = LISTENING_SECTIONS.flatMap((section) => section.questions);


